djangoProject/urls.py
from django.conf import settings
from django.urls import path, re_path
from django.views.static import serve

from app01.views import depart, user, admin, account, chart, city

urlpatterns = [
    # 部门管理
    path('depart/list/', depart.depart_list),
    path('depart/add/', depart.depart_add),
    path('depart/detail/', depart.depart_detail),
    path('depart/edit/', depart.depart_edit),
    path('depart/delete/', depart.depart_delete),
    path('depart/multipart/add/', depart.depart_multipart_add),

    # 员工管理
    path('user/list/', user.user_list),
    path('user/add/', user.user_add),
    path('user/detail/', user.user_detail),
    path('user/edit/', user.user_edit),
    path('user/delete/', user.user_delete),

    # 管理员
    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.admin_add),
    path('admin/edit/', admin.admin_edit),
    path('admin/reset/', admin.admin_reset),
    path('admin/delete/', admin.admin_delete),

    # 登录
    path('login/', account.login),
    path('image/code/', account.image_code),
    path('logout/', account.logout),

    # 数据统计
    path('', chart.chart_list),
    path('chart/list/', chart.chart_list),
    path('chart/line/', chart.chart_line),
    path('chart/bar/', chart.chart_bar),
    path('chart/pie/', chart.chart_pie),

    # 城市列表
    path('city/list/', city.city_list),
    path('city/add/', city.city_add),
    path('city/delete/', city.city_delete),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
]

app01/models.py
"""
在终端Terminal中先后执行以下两条命令 创建数据库表：
    python manage.py makemigrations
    python manage.py migrate
# 在终端Terminal中执行以下任意一条命令 创建另一模块：
    python manage.py startapp app02
    或 django-admin startapp app02
"""
from django.db import models


class Department(models.Model):
    """ 部门表 """
    title = models.CharField(verbose_name='部门名称', max_length=32)

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """ 员工表 """
    name = models.CharField(verbose_name="姓名", max_length=16)
    gender_choices = (
        (1, "男"),
        (2, "女"),
    )
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices, default=1)
    create_date = models.DateField(verbose_name="入职时间")
    depart = models.ForeignKey(verbose_name="部门", to="Department", to_field="id", on_delete=models.CASCADE,
                               default=49)
    account = models.DecimalField(verbose_name="月薪", max_digits=10, decimal_places=2, default=8000)
    mobile = models.CharField(verbose_name="手机号码", max_length=11)
    birth_date = models.DateField(verbose_name="出生日期")


class Admin(models.Model):
    """ 管理员 """
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)

    def __str__(self):
        return self.username


class City(models.Model):
    """ 城市 """
    name = models.CharField(verbose_name="名称", max_length=32)
    count = models.IntegerField(verbose_name="人口")
    img = models.FileField(verbose_name="Logo", max_length=128, upload_to='city/')

templates/add_edit.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"> {{ panel_title }} </h3>
        </div>
        <div class="panel-body">
            <form method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    <label>{{ field.label }}</label>
                    {{ field }}
                    <span style="color: red;">{{ field.errors.0 }}</span>
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">提 交</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
<script>
    $(function () {
        $('#id_create_date').datepicker({
            format: 'yyyy-mm-dd',
            todayHighlight: true,
            language: "zh-CN",
            autoclose: true
        });
        $('#id_birth_date').datepicker({
            format: 'yyyy-mm-dd',
            todayHighlight: true,
            language: "zh-CN",
            autoclose: true
        });
    })
</script>
{% endblock %}

templates/admin_list.html
{% extends 'layout.html' %}
{% block content %}
<div class="container" style="width: 80%; margin: auto">
    <!--    新建按钮与搜索框    -->
    <div class="clearfix" style="margin-bottom: 5px">
        <a class="btn btn-success" href="/admin/add/">
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
            <span>新增管理员</span>
        </a>
        <div style="float: right; width: 300px;">
            <form method="get">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="Search for username"
                           value="{{ search_data }}">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                    </span>
                </div>
            </form>
        </div>
    </div>
    <!--    列表    -->
    <div class="panel panel-primary" style="margin-bottom: 0">
        <div class="panel-heading">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            <span class="panel-title">管理员列表</span>
        </div>
        <table class="table table-bordered table-hover text-center">
            <thead>
            <tr>
                <th style="text-align: center;">ID</th>
                <th style="text-align: center;">账户</th>
                <th style="text-align: center;">密码</th>
                <th style="text-align: center;">操作</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in queryset %}
            <tr>
                <td>{{ obj.id }}</td>
                <td>{{ obj.username }}</td>
                <td>********</td>
                <td>
                    <a class="btn btn-primary btn-xs" href="/admin/edit/?nid={{ obj.id }}">编辑</a>
                    <a class="btn btn-primary btn-xs" href="/admin/reset/?nid={{ obj.id }}">重置密码</a>
                    <a class="btn btn-danger btn-xs" href="/admin/delete/?nid={{ obj.id }}">删除</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <!--    页码    -->
    <ul class="pagination" style="margin: 6px 0">
        {{ page_string }}
    </ul>
</div>
{% endblock %}

templates/chart_list.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<div class="container" style="width: 80%; margin: auto">
    <div class="panel panel-primary">
        <div class="panel-heading">折线图</div>
        <div class="panel-body">
            <div id="m1" style="width: 100%;height: 400px"></div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-8">
            <div class="panel panel-primary">
                <div class="panel-heading">柱状图</div>
                <div class="panel-body">
                    <div id="m2" style="width: 100%;height: 400px;"></div>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="panel panel-primary">
                <div class="panel-heading">饼图</div>
                <div class="panel-body">
                    <div id="m3" style="width: 100%;height: 400px;"></div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block js %}
<script src="{% static 'js/echarts.js' %}"></script>
<script type="text/javascript">
    $(function () {
        initLine();
        initBar();
        initPie();
    })

    /**
     * 初始化折线图
     */
    function initLine() {
        var myChart = echarts.init(document.getElementById('m1'));
        var option = {
            title: {
                text: '分公司业绩图',
                left: "center",
            },
            tooltip: {
                trigger: 'axis'
            },
            legend: {
                data: [],
                bottom: 0
            },
            toolbox: {
                feature: {
                    saveAsImage: {}
                }
            },
            xAxis: {
                type: 'category',
                boundaryGap: false,
                data: []
            },
            yAxis: {
                type: 'value'
            },
            series: []
        };
        $.ajax({
            url: '/chart/line/',
            type: "get",
            dataType: "JSON",
            success: function (res) {
                if (res.status) {
                    option.legend.data = res.data.legend;
                    option.xAxis.data = res.data.x_axis;
                    option.series = res.data.series_list;
                    myChart.setOption(option);
                }
            }
        })
    }

    /**
     * 初始化柱状图
     */
    function initBar() {
        var myChart = echarts.init(document.getElementById('m2'));
        var option = {
            title: {
                text: '员工业绩阅读汇总信息',
                textAlign: "auto",
                left: "center",
            },
            tooltip: {},
            legend: {
                data: [],
                bottom: 0
            },
            toolbox: {
                feature: {
                    saveAsImage: {}
                }
            },
            xAxis: {
                data: []
            },
            yAxis: {},
            series: []
        };
        $.ajax({
            url: "/chart/bar/",
            type: "get",
            dataType: "JSON",
            success: function (res) {
                if (res.status) {
                    option.legend.data = res.data.legend;
                    option.xAxis.data = res.data.x_axis;
                    option.series = res.data.series_list;
                    myChart.setOption(option);
                }
            }
        })
    }

    /**
     * 初始化饼状图
     */
    function initPie() {
        var myChart = echarts.init(document.getElementById('m3'));
        var option = {
            title: {
                text: '部门预算占比',
                subtext: '广西分公司',
                left: 'center'
            },
            tooltip: {
                trigger: 'item'
            },
            toolbox: {
                feature: {
                    saveAsImage: {}
                }
            },
            legend: {
                bottom: 0
            },
            series: [
                {
                    name: '预算',
                    type: 'pie',
                    radius: '50%',
                    data: [],
                    emphasis: {
                        itemStyle: {
                            shadowBlur: 10,
                            shadowOffsetX: 0,
                            shadowColor: 'rgba(0, 0, 0, 0.5)'
                        }
                    }
                }
            ]
        };
        $.ajax({
            url: "/chart/pie/",
            type: "get",
            dataType: "JSON",
            success: function (res) {
                if (res.status) {
                    option.series[0].data = res.data;
                    myChart.setOption(option);
                }
            }
        })
    }
</script>
{% endblock %}

templates/city_list.html
{% extends 'layout.html' %}
{% block content %}
<div class="container" style="width: 80%; margin: auto">
    <!--    新建按钮    -->
    <div style="margin-bottom: 10px">
        <a class="btn btn-success" data-toggle="modal" data-target="#addEditModal">
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
            新建城市
        </a>
    </div>
    <!--    列表    -->
    <div class="panel panel-primary">
        <div class="panel-heading">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            城市列表
        </div>
        <table class="table table-bordered text-center">
            <thead>
            <tr>
                <th style="text-align: center;">ID</th>
                <th style="text-align: center;">Logo</th>
                <th style="text-align: center;">名称</th>
                <th style="text-align: center;">人口</th>
                <th style="text-align: center;">操作</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in queryset %}
            <tr>
                <td>{{ obj.id }}</td>
                <td>
                    <img src="/media/{{ obj.img }}" style="height: 100px;">
                </td>
                <td>{{ obj.name }}</td>
                <td>{{ obj.count }}</td>
                <td>
                    <input delete_id="{{ obj.id }}" delete_title="{{ obj.name }}" type="button"
                           class="btn btn-danger btn-xs btnDelete" value="删除">
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<!-- 新建/编辑（弹窗对话框） -->
<div class="modal fade" id="addEditModal" tabindex="-1" role="dialog" aria-labelledby="addEditModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="addEditModalLabel">新增城市</h4>
            </div>
            <div class="modal-body">
                <form method="post" enctype="multipart/form-data" novalidate action="/city/add/">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        <label>{{ field.label }}</label>
                        {{ field }}
                        <span style="color: red;">{{ field.errors.0 }}</span>
                    </div>
                    {% endfor %}
                    <div style="text-align: right;">
                        <button type="submit" class="btn btn-primary">提 交</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block js %}
<script type="text/javascript">
    $(function () {
        $(".btnDelete").click(function () {
            var DELETE_ID = $(this).attr("delete_id");
            var delete_title = $(this).attr("delete_title");
            var tip_text = "是否确认删除[ " + delete_title + " ]?"
            if (confirm(tip_text)) {
                $.ajax({
                    url: "/city/delete/",
                    type: "GET",
                    data: {
                        delete_id: DELETE_ID
                    },
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            location.reload();
                        } else {
                            alert(res.error);
                        }
                    }
                })
            }
        })
    })
</script>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DjangoProject</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .navbar {
            border-radius: 0;
        }

        .navbar-default .navbar-nav > li > a:hover,
        .navbar-default .navbar-nav > li > a:focus {
            color: #337AB7;
            background-color: #e7e7e7;
        }

        body {
            padding-top: 60px;
        }
    </style>
    {% block css %}{% endblock %}
</head>
<body>
<!--  导航条  -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/chart/list/"> DjangoProject </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="/depart/list/">部门</a></li>
                <li><a href="/user/list/">员工</a></li>
                <li><a href="/admin/list/">管理员</a></li>
                <li><a href="/chart/list/">数据统计</a></li>
                <li><a href="/city/list/">文件上传</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">{{ request.session.info.name }}<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">相关跳转链接</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="/logout/">注 销</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block content %}{% endblock %}

<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
{% block js %}{% endblock %}
</body>
</html>

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }

        .account h2 {
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="account">
    <h2>用户登录</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label>{{ form.username.label }}</label>
            {{ form.username }}
            <span style="color: red;">{{ form.username.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label>{{ form.password.label }}</label>
            {{ form.password }}
            <span style="color: red;">{{ form.password.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label>{{ form.code.label }}</label>
            <div class="row">
                <div class="col-xs-7">
                    {{ form.code }}
                    <span style="color: red;">{{ form.code.errors.0 }}</span>
                </div>
                <div class="col-xs-5">
                    <img id="image_code" src="/image/code/" style="width: 125px;"
                         onclick="this.setAttribute('src','/image/code/?random='+Math.random())">
                </div>
            </div>
        </div>
        <input type="submit" value="登 录" class="btn btn-primary">
    </form>
</div>
</body>
</html>

templates/user_list.html
{% extends 'layout.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}


{% block content %}
<div class="container">
    <!--    新建按钮与搜索框    -->
    <div class="clearfix" style="margin-bottom: 5px">
        <a id="btnAdd" class="btn btn-success">
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
            <span>新增员工</span>
        </a>
        <div style="float: right; width: 300px;">
            <form method="get">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="Search for name"
                           value="{{ search_data }}">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                    </span>
                </div>
            </form>
        </div>
    </div>
    <!--    列表    -->
    <div class="panel panel-primary" style="margin-bottom: 0">
        <div class="panel-heading">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            <span class="panel-title">员工列表</span>
        </div>
        <table class="table table-bordered table-hover text-center">
            <thead>
            <tr>
                <th style="text-align: center;">ID</th>
                <th style="text-align: center;">姓名</th>
                <th style="text-align: center;">性别</th>
                <th style="text-align: center;">入职时间</th>
                <th style="text-align: center;">部门</th>
                <th style="text-align: center;">月薪</th>
                <th style="text-align: center;">手机号码</th>
                <th style="text-align: center;">出生日期</th>
                <th style="text-align: center;">操作</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in queryset %}
            <tr>
                <td>{{ obj.id }}</td>
                <td>{{ obj.name }}</td>
                <td>{{ obj.get_gender_display }}</td>
                <td>{{ obj.create_date|date:"Y-m-d" }}</td>
                <td>{{ obj.depart.title }}</td>
                <td>{{ obj.account }}</td>
                <td>{{ obj.mobile }}</td>
                <td>{{ obj.birth_date|date:"Y-m-d" }}</td>
                <td>
                    <input edit_id="{{ obj.id }}" type="button" class="btn btn-primary btn-xs btnEdit" value="编辑">
                    <input delete_id="{{ obj.id }}" delete_title="{{ obj.name }}" type="button"
                           class="btn btn-danger btn-xs btnDelete" value="删除">
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <!--    页码    -->
    <ul class="pagination" style="margin: 6px 0">
        {{ page_string }}
    </ul>
</div>
<!-- 新建/编辑（弹窗对话框） -->
<div class="modal fade" id="addEditModal" tabindex="-1" role="dialog" aria-labelledby="addEditModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="addEditModalLabel"></h4>
            </div>
            <div class="modal-body">
                <form id="addEditForm">
                    <div class="clearfix">
                        {% for field in form %}
                        <div class="col-xs-6">
                            <div class="form-group" style="position: relative; margin-bottom: 20px;">
                                <label>{{ field.label }}</label>
                                {{ field }}
                                <span class="errorMsg" style="color: red; position: absolute;"></span>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button id="btnSave" type="button" class="btn btn-primary">保 存</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
            </div>
        </div>
    </div>
</div>
<!-- 删除（弹窗对话框） -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="alert alert-danger alert-dismissible fade in" role="alert">
            <h4 id="tip_text"></h4>
            <p style="text-align: right;">
                <button id="btnConfirmDelete" type="button" class="btn btn-danger">确 定</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
            </p>
        </div>
    </div>
</div>
{% endblock %}


{% block js %}
<script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
<script>
    $(function () {
        $('#id_create_date').datepicker({
            format: 'yyyy-mm-dd',
            todayHighlight: true,
            language: "zh-CN",
            autoclose: true
        });
        $('#id_birth_date').datepicker({
            format: 'yyyy-mm-dd',
            todayHighlight: true,
            language: "zh-CN",
            autoclose: true
        });
    })
</script>
<script type="text/javascript">
    var EDIT_ID;
    var DELETE_ID;

    $(function () {
        bindBtnAddEvent();
        bindBtnSaveEvent();
        bindBtnEditEvent();
        bindBtnDeleteEvent();
        bindBtnConfirmDeleteEvent();
    })

    function bindBtnAddEvent() {
        $("#btnAdd").click(function () {
            EDIT_ID = undefined;
            $("#addEditForm")[0].reset();
            $("#addEditModalLabel").text("新建部门");
            $('#addEditModal').modal('show');
        })
    }

    function bindBtnSaveEvent() {
        $("#btnSave").click(function () {
            $(".errorMsg").empty();
            if (EDIT_ID) {
                doEdit();
            } else {
                doAdd();
            }
        })
    }

    function doAdd() {
        $.ajax({
            url: "/user/add/",
            type: "post",
            data: $("#addEditForm").serialize(),
            dataType: "JSON",
            success: function (res) {
                if (res.status) {
                    $("#addEditForm")[0].reset();
                    $('#addEditModal').modal('hide');
                    location.reload();
                } else {
                    $.each(res.error, function (name, errorList) {
                        $("#id_" + name).next().text(errorList[0]);
                    })
                }
            }
        })
    }

    function bindBtnEditEvent() {
        $(".btnEdit").click(function () {
            $("#addEditForm")[0].reset();
            EDIT_ID = $(this).attr("edit_id");
            $.ajax({
                url: "/user/detail/",
                type: "get",
                data: {
                    edit_id: EDIT_ID
                },
                dataType: "JSON",
                success: function (res) {
                    if (res.status) {
                        $.each(res.data, function (name, value) {
                            $("#id_" + name).val(value);
                        })
                        $("#addEditModalLabel").text("员工信息更改");
                        $('#addEditModal').modal('show');
                    } else {
                        alert(res.error);
                    }
                }
            })
        })
    }

    function doEdit() {
        $.ajax({
            url: "/user/edit/" + "?edit_id=" + EDIT_ID,
            type: "post",
            data: $("#addEditForm").serialize(),
            dataType: "JSON",
            success: function (res) {
                if (res.status) {
                    $("#addEditForm")[0].reset();
                    $('#addEditModal').modal('hide');
                    location.reload();
                } else {
                    if (res.tips) {
                        alert(res.tips);
                    } else {
                        $.each(res.error, function (name, errorList) {
                            $("#id_" + name).next().text(errorList[0]);
                        })
                    }
                }
            }
        })
    }

    function bindBtnDeleteEvent() {
        $(".btnDelete").click(function () {
            DELETE_ID = $(this).attr("delete_id");
            var delete_title = $(this).attr("delete_title");
            var tip_text = "是否确认删除[ " + delete_title + " ]?"
            $("#tip_text").text(tip_text)
            $("#deleteModal").modal('show');
        })
    }

    function bindBtnConfirmDeleteEvent() {
        $("#btnConfirmDelete").click(function () {
            $.ajax({
                url: "/user/delete/",
                type: "GET",
                data: {
                    delete_id: DELETE_ID
                },
                dataType: "JSON",
                success: function (res) {
                    if (res.status) {
                        $("#deleteModal").modal('hide');
                        location.reload();
                    } else {
                        alert(res.error);
                    }
                }
            })
        })
    }
</script>
{% endblock %}